export const UserAction = {
  LOGIN: 'LOGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGOUT: 'LOGOUT',
  GET_INFO: 'GET_INFO',
  GET_INFO_SUCCESS: 'GET_INFO_SUCCESS',
  GET_INFO_FAILURE: 'GET_INFO_FAILURE',
};

export const UsersAction = {
  GET_USERS: 'GET_USERS',
  GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
};

export const ModalAction = {
  SHOW_MODAL: 'SHOW_MODAL',
};

export const OOORequestAction = {
  GET_MY_OOO_REQUESTS: 'GET_MY_OOO_REQUESTS',
  CANCEL_MY_OOO_REQUEST: 'CANCEL_MY_OOO_REQUEST',
  SUBMIT_MY_OOO_REQUEST: 'SUBMIT_MY_OOO_REQUEST',
  SUBMIT_REJECT_REASON: 'SUBMIT_REJECT_REASON',
  GET_ADMIN_OOO_REQUEST: 'GET_ADMIN_OOO_REQUEST',
  APPROVE_MENTEE_OOO_REQUEST: 'APPROVE_MENTEE_OOO_REQUEST:',
  REJECT_MENTEE_OOO_REQUEST: 'REJECT_MENTEE_OOO_REQUEST:',
  GET_MENTEES_REQUEST: 'GET_MENTEES_REQUEST',

};
